# Generated by Django 4.1.3 on 2023-07-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('qr_code', 'QR Code')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
