# Generated by Django 4.1.3 on 2023-07-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('Chityala', 'Chityala'), ('Others', 'Others')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
