# Generated by Django 4.1.3 on 2023-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_type',
            field=models.CharField(choices=[('Chityala', 'Chityala'), ('Others', 'Others')], default='Chityala', max_length=10),
        ),
    ]
