# Generated by Django 4.1.3 on 2023-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('Other', 'Other'), ('rozerpay', 'Rozer Pay')], max_length=20),
        ),
    ]
